version: '3'
services:
  web:
    build: .
    ports:
      - "100:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=password
      - SECRET_KEY=supersecretkey  # Variabile d'ambiente per la chiave segreta
